### ISSUE TITLE
Feature Request Heading anchors and anchor links

### ISSUE THREAD

**Issue by tyson-nw** [elazar/league-commonmark-obsidian#2]
Obsidian automatically creates anchors for each heading named after the heading. It also has `[[#heading]]` that lets you link to headings in the same page.

Would it be possible to make the headings linkable like Obsidian?

**Comment by elazar** [comment]
@tyson-nw Were you able to sort out how to do this?

**Comment by tyson-nw** [comment]
Mostly, I was able to write some specific parsers that handle it.

**Comment by elazar** [comment]
@tyson-nw Sorry, probably should've communicated this sooner: I had a busy first week at a new job, but was planning on looking into your issue over the weekend. If you'd like to submit a PR and details of any areas you want to improve or add to, I'd be happy to look over them. 🙂
